### ISSUE TITLE
!love% doesn't work

### ISSUE THREAD

**Issue by Mask1nen** [nightbloo/nb3bot#5]

**Comment by Larry1123** [comment]
I will get on this as soon as I can.

**Comment by Pik-achu** [comment]
i cant understand why it doesn work . I just checked it and i dont see mistkaes but i might be a scrub :x:

**Comment by netux** [comment]
Little argument length error, my bad. It's [fixed now](https://github.com/nightbloo/nb3bot/commit/8261d0f06ade94fe076ca32daf6df37edd6f82d2) :)
