### ISSUE TITLE
Netux twitch link is malfunctioning!

### ISSUE THREAD

**Issue by Pik-achu** [nightbloo/nb3bot#7]
Anyone who can help please do! People can **\* (snip) ***!!! (dont tell anyone)

**Comment by netux** [comment]
I'm currently on vacation an will be for one more week. Sorry :c

Will work on it ss soon as I get back.

**Comment by Pik-achu** [comment]
Ow that explains a lot :) Add me on skype netux. It is Kaberos2

I can tell you about malfunctions and other stuff since larrys pc died

**Comment by netux** [comment]
Will do when I get back, sorry about the BOT :S

**Comment by Larry1123** [comment]
When I get my desktop working once more if this is not done yet I will look into it.
